# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  reddit_zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    networks:
      - reddit_net
  reddit_kafka:
    image: kafka-docker
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: reddit_kafka
      KAFKA_ZOOKEEPER_CONNECT: reddit_zookeeper:2181
    depends_on:
      - reddit_zookeeper
    networks:
      - reddit_net
  redis_cache:
    container_name: redis_cache
    image: redis
    expose:
      - "6379"
    # ports:
    #   - "6379:6379"
    networks:
      - reddit_net
  reddit_mongo:
    container_name: reddit_mongo
    image: mongo:latest
    expose:
      - "27017"
    # ports:
    #   - '27017:27017'
    logging: 
      driver: none
    networks:
      - reddit_net
  reddit_backend:
    container_name: reddit_backend
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    command: npm run start:dev
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - reddit_mongo
      # - reddit_db
      - reddit_kafka
    networks:
      - reddit_net
  reddit_kafka_backend:
    container_name: reddit_kafka_backend
    build:
      context: ./Reddit-Kafka
    volumes:
      - ./Reddit-Kafka:/usr/src/reddit-kafka-backend
    command: npm run start
    depends_on:
      - reddit_mongo
      - reddit_db
      - reddit_kafka
      - reddit_backend
    depends_on:
      - reddit_mongo
      - redis_cache
    networks:
      - reddit_net
  # reddit_frontend:
  #   container_name: reddit_frontend
  #   build:
  #     context: ./reddit-frontend
  #     # dockerfile: ./reddit-backend/Dockerfile
  #   volumes:
  #     - ./reddit-frontend:/usr/src/reddit-frontend
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - reddit_backend
  #   networks:
  #     - reddit_net

networks:
  reddit_net:
    driver: bridge
