# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  reddit_zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    networks:
      - reddit_net
  reddit_kafka:
    image: kafka-docker
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: reddit_kafka
      KAFKA_ZOOKEEPER_CONNECT: reddit_zookeeper:2181
    depends_on:
      - reddit_zookeeper
    networks:
      - reddit_net
  redis_cache:
    container_name: redis_cache
    image: redis
    expose:
      - "6379"
    # ports:
    #   - "6379:6379"
    networks:
      - reddit_net
  reddit_mongo:
    container_name: reddit_mongo
    image: mongo:latest
    expose:
      - "27017"
    # ports:
    #   - '27017:27017'
    logging: 
      driver: none
    networks:
      - reddit_net
  reddit_backend_1:
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    environment: 
      GROUP_ID: reddit_backend_1
      LISTEN_TOPIC_NAME: messages_response_1
    command: npm run start:dev
    expose:
      - "8000"
    # ports:
    #   - "8000-8005:8000"
    depends_on:
      - reddit_mongo
      - reddit_kafka
    networks:
      - reddit_net
  reddit_backend_2:
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    environment: 
      GROUP_ID: reddit_backend_2
      LISTEN_TOPIC_NAME: messages_response_2
    command: npm run start:dev
    expose:
      - "8000"
    # ports:
    #   - "8000-8005:8000"
    depends_on:
      - reddit_mongo
      - reddit_kafka
    networks:
      - reddit_net
  reddit_backend_3:
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    environment: 
      GROUP_ID: reddit_backend_3
      LISTEN_TOPIC_NAME: messages_response_3
    command: npm run start:dev
    expose:
      - "8000"
    # ports:
    #   - "8000-8005:8000"
    depends_on:
      - reddit_mongo
      - reddit_kafka
    networks:
      - reddit_net
  reddit_backend_4:
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    environment: 
      GROUP_ID: reddit_backend_4
      LISTEN_TOPIC_NAME: messages_response_4
    command: npm run start:dev
    expose:
      - "8000"
    # ports:
    #   - "8000-8005:8000"
    depends_on:
      - reddit_mongo
      - reddit_kafka
    networks:
      - reddit_net
  reddit_kafka_backend:
    # container_name: reddit_kafka_backend
    build:
      context: ./Reddit-Kafka
    volumes:
      - ./Reddit-Kafka:/usr/src/reddit-kafka-backend
    command: npm run start
    depends_on:
      - reddit_mongo
      - reddit_db
      - reddit_kafka
      - reddit_backend
    depends_on:
      - reddit_mongo
      - redis_cache
    networks:
      - reddit_net
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reddit_backend_1
      - reddit_backend_2
      - reddit_backend_3
      - reddit_backend_4
    ports:
      - "8080:8080"
    networks:
      - reddit_net

networks:
  reddit_net:
    driver: bridge
