# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  reddit-db:
    container_name: reddit-db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=reddit-dev
      - DATABASE_HOST=reddit-db
    expose:
      - "5432"
    networks:
      - reddit_net
    logging:
      driver: none
  reddit_mongo:
    container_name: reddit_mongo
    image: mongo:latest
    expose:
      - "27017"
    logging:
      driver: none
    networks:
      - reddit_net
  reddit_backend:
    container_name: reddit_backend
    build:
      context: .
    volumes:
      - ./:/usr/src/reddit-backend
    command: npm run start:dev
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - reddit_mongo
      - reddit-db
    networks:
      - reddit_net
  # reddit_frontend:
  #   container_name: reddit_frontend
  #   build:
  #     context: ./reddit-frontend
  #     # dockerfile: ./reddit-backend/Dockerfile
  #   volumes:
  #     - ./reddit-frontend:/usr/src/reddit-frontend
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - reddit_backend
  #   networks:
  #     - reddit_net

networks:
  reddit_net:
    driver: bridge
